spring:
  application:
    name: updated-product-query-service

  datasource:
    url: jdbc:mysql://localhost:3306/microservice_cqrs
    username: root
    password: manager

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.programming.response

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 9091
